steps:
- id: "Instalando"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'hpa']
  env: ['GOPATH=.']

- id: "Teste unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['test','hpa']
  env: ['GOPATH=.']
 
- id: "Building image from Dockerfile"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go:$SHORT_SHA', '-f', 'Dockerfile', '.']

- id: "Pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go:$SHORT_SHA']

- id: "Adjusting deployment file - k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
          sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go:$SHORT_SHA#g' deployment.yaml > deployment-new.yaml;

- id: "Deploying k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
          - 'apply'
          - '-f'
          - 'deployment-new.yaml'
  env:
          - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
          - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-go'
