steps:
- id: "Instalando"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'hpa']
  env: ['GOPATH=.']

- id: "Teste unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['test','hpa']
  env: ['GOPATH=.']
