apiVersion: apps/v1
kind: Deployment
metadata:
        name: go
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: go
        template:
               metadata:
                       labels:
                            app: go
               spec:
                       containers:
                       - name: go
                         image: img-app-deployment
                         #image: marcosbacci/go-hpa:latest
                         ports:
                         - containerPort: 9000

                           #resources:
                           #      requests:
                           #              cpu: "50m"
                           #     limits:
                           #             cpu: "100m"

